name = "ipd-next"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = ".vercel/output/static"

[[d1_databases]]
binding = "DB"
database_name = "ipd-productivity"
database_id = "992fb2c5-7dee-4fb6-8da1-baf4670feb54"
